project_name: cometbft

env:
  # Require use of Go modules.
  - GO111MODULE=on

builds:
<<<<<<< HEAD
  - id: "Tendermint"
    main: ./cmd/tendermint/main.go
=======
  - id: "cometbft"
    main: ./cmd/cometbft/main.go
>>>>>>> 1cb55d49b (Rename Tendermint to CometBFT: further actions (#224))
    ldflags:
      - -s -w -X github.com/cometbft/cometbft/version.TMCoreSemVer={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

release:
  prerelease: auto
  name_template: "{{.Version}}"

archives:
  - files:
      - LICENSE
      - README.md
      - UPGRADING.md
      - SECURITY.md
      - CHANGELOG.md
